export const FETCH_GAME_STATE_REQUEST = 'FETCH_GAME_STATE_REQUEST';
export const FETCH_GAME_STATE_SUCCESS = 'FETCH_GAME_STATE_SUCCESS';
export const FETCH_GAME_STATE_FAILURE = 'FETCH_GAME_STATE_FAILURE';

export const UPDATE_SQUARE_REQUEST = 'UPDATE_SQUARE_REQUEST';
export const UPDATE_SQUARE_SUCCESS = 'UPDATE_SQUARE_SUCCESS';
export const UPDATE_SQUARE_FAILURE = 'UPDATE_SQUARE_FAILURE';

